### PR TITLE
Call & CallToolbar test expansion

### PR DESCRIPTION
**Pull request by jacogr**
Also has an (unintended/side-effect) fix for the failing test in https://github.com/ethcore/parity-dapps-status/pull/174 & https://github.com/ethcore/parity-dapps-status/pull/177

PS: We should switch on the protected branched feature and ensure that (a) all checks pass & (b) updated with master branch (at least in the PR) before merging

### CODE REVIEW

**Comment by goldylucks** [comment]
protected branch u mean not commiting directly to master?
it isn't enabled?

for PRs we can c if all checks pass and if there r conflicts
(not sure if that's what u meant)

**Comment by jacogr** [comment]
Yes, exactly what is does, basically 

https://help.github.com/articles/about-protected-branches/

In addition (and this actually does drive me crazy when my at-work review & merge queue is large, but the benefits outweigh the rest) it can only allow merges when the branch is up to date with master in addition to the passing checks.

Basically, say you have PR1 & Pr2 in line. Both up to date. You merge PR1, then PR2 will need to be updated first (single button click on GithHub, no dev intervention) before it can be merged. It does add extra safety, but with many serial merges it does delay things a bit.

**Comment by goldylucks** [comment]
so u always merge master into a branch before merging the branch's pr to master?

**Comment by jacogr** [comment]
Yes. Admins can still override if need-be, but in most cases worth the effort. This is how it operates (link from the original link I supplied) -

https://help.github.com/articles/about-required-status-checks/

You can see the "Update Branch" button as well as the Admin override if need be. Just some extra protection. 

In my current day-job we actually did switch off the Admin override, but as I mentioned when the queue is full it can be a nightmare, i.e. when I'm sitting with a queue of merges and 12 minutes build times, some swearing do occur.

**Comment by tomusdrw** [comment]
Enabled to test how it works.

**Pull request merged**
